# Generated by Django 4.1.1 on 2022-09-16 14:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_restaurantmodel_address_restaurantmodel_contact_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantmodel',
            name='contact_no',
            field=models.CharField(default='unknown', max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number is not correct', regex='^[0-9\\-\\+]{9,15}$')]),
        ),
        migrations.CreateModel(
            name='VoteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted_at', models.DateField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.employeemodel')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.menumodel')),
            ],
        ),
    ]
